version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  api_gateway:
    build: ./backend/api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=sqlite:///./sql_app.db
    volumes:
      - ./data:/app/data

  mother_ai:
    build: ./backend/mother_ai
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=sqlite:///./sql_app.db
    volumes:
      - ./data:/app/data

  text_agent:
    build: ./backend/agents/text_agent
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./data:/app/data

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - api_gateway

volumes:
  redis_data:

